version: "3.8"

services:
  otus-db:
    image: postgres:15
    container_name: otus_db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zelenodolsk9
      POSTGRES_DB: otus_db
